version: '3'
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
  service:
    build: ./service
    ports:
      - "8080:8080"
  db:
    container_name: challenge_db
    build: ./db/postgres
    env_file:
      - ./db/.env
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  db:
    external: true